### ISSUE TITLE
Carta no mobile

### ISSUE THREAD

**Issue by murilodpl** [f4dul/yugioh-card-search-engine#3]
Tava dando uma olhada no repo rodando no heroku e achei brabissimo, mt pica. Dai fui ver como tava o responsivo pra ver como estava sendo colocado o footer e me liguei que a partir de 314px de largura a imagem começa a quebrar.

Só uma coisa besta que um width: 100% em um media já resolve, espero não ser levado a mal, gostei do projeto e queria só dar uma força. 😎🖤

**Comment by murilodpl** [comment]
Criei um PR com o ajuste #4 , bem simplão.

**Comment by evandrofadul** [comment]
Thanks, bro!
